### ISSUE TITLE
Resolving Import Errors (Red Files) After Template Generation

### ISSUE THREAD

**Issue by TejasGhatte** [csivitu/go-sail#5]
When populating a directory after generating a project template, it is crucial to resolve any import errors (commonly referred to as "red files") that may appear in the IDE. These errors typically indicate issues such as missing dependencies, incorrect paths, or improperly configured module imports. The user should not encounter any red files in their project, and all necessary imports must be correctly configured to ensure smooth development.

**Comment by sarveshdakhore** [comment]
what exactly do you want, when I am creating a project lets say 'hello' via
sarveshdakhore@Sarveshs-MacBook-Pro go-sail % ./go-sail2 create hello
? 🚀 Choose a Go framework: fiber
? 💾 Choose a database (or None): mysql
? 🔗 Choose an ORM (or None): sqlx

then in file name database.go there are import errors so should I remove all the imports and keep the template like
package initializers

func ConnectDB() {
	
}


or should I install them or do something so that the error gets resolved?

**Comment by TejasGhatte** [comment]
Yes basically unused imports should be removed and required imports should be downloded
